### ISSUE TITLE
Distribute a "CLI client only" binary

### ISSUE THREAD

**Issue by nneul** [openbao/openbao#162] opened 2024-02-29 18:28 UTC
**Is your feature request related to a problem? Please describe.**
Every time I install 'vault' as a cli tool, it's packaging/content on most distros results in provisioning and starting the full service including generating cert/etc, when the majority of the time, all I want is the CLI tool. The binary is also excessively large (384MB on the last one I looked at) when only the client pieces are needed.

**Describe the solution you'd like**
Provide a stripped down client-only binary without the server components.

**Comment by cipherboy** [comment] 2024-03-01 13:01
\o Hello @nneul -- this is a duplicate of #73. :-) 

I had started down [this path earlier](https://github.com/cipherboy/openbao/commit/463ed892ccab4a1e4a2aabcbbec0a622bba06314) before realizing that it will be substantial work. I _think_ what needs to happen is, for each file in `command/` it is evaluated for needing to be in a particular binary, and adding tags to the same effect. I don't think that's sufficient though, as binary sizes will still be large... I think we've gotta evaluate the imports of the files as well, and where the import isn't necessary for all modes that requires a file, split the file, so that the import isn't present for the other modes (and thus, isn't included in the build for the other modes that don't need it). 

What I'm hoping to avoid is having to push build tags all the way into the other parts of Vault (past `command/` into `builtin/` or `vault/`)... 

I'd welcome your help with it, if you're interested!

**Closed** 2024-03-01 13:05 UTC
Labels: feature
