### ISSUE TITLE
[docs] broken production hardening link on quickstart

### ISSUE THREAD

**Issue by vtrenton** [openbao/openbao#308] opened 2024-04-27 04:18 UTC
**Describe the bug**
broken link to non-existant production hardening page in the quickstart. On the warning message stating that this is a dev install it references a dead link here:
https://openbao.org/docs/get-started/developer-qs/#step-1-start-openbao

> this [page](https://openbao.org/tutorials/operations/production-hardening/) provides some guidance on how to make your setup more production-friendly.

**To Reproduce**
1. Go to docs
2. navigate to getting started > Developer quick start > Step 1: start OpenBao
3. click on link in the warning message

**Expected behavior**
Valid link

**Comment by cipherboy** [comment] 2024-04-27 15:33
I think this is a duplicate of #303 and #151 as well, links with `/tutorials/` in them won't work. I'll address this and #303 altogether by removing the links, but we don't have tutorials until someone volunteers to write them.

**Closed** 2024-05-03 14:24 UTC
Labels: bug
