### ISSUE TITLE
Failed to set process secure bits

### ISSUE THREAD

**Issue by in0rdr** [openbao/openbao#419] opened 2024-07-20 10:02 UTC
After the upgrade from v2.0.0-beta20240618 to v2.0.0, I was unable to start bao server.

The systemd service unit fails with the following message:
```
Jul 19 21:03:18 systemd[1]: Starting "OpenBao - A tool for managing secrets"...
Jul 19 21:03:18 systemd[1820]: openbao.service: Failed to set process secure bits: Operation not permitted
Jul 19 21:03:18 systemd[1820]: openbao.service: Failed at step SECUREBITS spawning /usr/bin/bao: Operation not permitted
```

**Environment:**
* OpenBao Server Version 2.0.0
* OpenBao CLI Version 2.0.0
* Ubuntu 20.04.6 LTS (x86_64)

OpenBao server configuration file(s):

```hcl
ui = true

storage "file" {
  path = "/opt/openbao/data"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/openbao/tls/tls.crt"
  tls_key_file  = "/opt/openbao/tls/tls.key"
}
```

**Comment by cipherboy** [comment] 2024-07-20 12:03
@in0rdr Interesting! I'm able to reproduce this on 20.04, but not on Fedora 40. It looks like, for some reason, 20.04 still requires:

```
AmbientCapabilities=CAP_IPC_LOCK
CapabilityBoundingSet=CAP_IPC_LOCK
```

But I'm not quite sure why. Do you perhaps have ideas?

In #363 we've [removed mlock](https://openbao.org/docs/rfcs/mlock-removal/), so I'm surprised that it is still conditionally required.

Perhaps you have thoughts @IohannesArnold?

**Comment by in0rdr** [comment] 2024-07-20 12:40
Thank you @cipherboy for connecting it to the change. The suggested fix also works on my (old) machine. Using following variables in the service unit now:
```
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
AmbientCapabilities=CAP_IPC_LOCK
```

I already assumed it could be related to mlock, but only quickly skimmed through the docs in https://openbao.org/docs/rfcs/mlock-removal.

For now, I will probably update my old OS :smile: and read a bit more about the Systemd configuration variables and how they relate to mlock. Also, I'm going to rollout the new bao 2.0.0 on some more recent 12 (bookworm) machines to see the difference.

Thanks again, much appreciated.

**Comment by cipherboy** [comment] 2024-07-20 13:07
@in0rdr No problem, let us know what you find out! 

`MemorySwapMax` was [added in version 232](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#MemorySwapMax=bytes) and my 20.04 box is running 245 so that should be fine... I was wondering if perhaps there was some compatibility shim patch wherein it would try mlock if the unit file had this (newer) parameter, but that doesn't make sense given these versions. 

I wonder if there's an Ubuntu- or Debain-specific patch somewhere in our dependencies? We have:

```
github.com/hashicorp/go-secure-stdlib/mlock v0.1.3 // indirect
```

so it could be on some system we're invoking it somehow.

**Comment by in0rdr** [comment] 2024-07-20 13:39
As expected, the issue does not occur on 22.04.4 LTS. Also, it does not seem to be an issue on Debian 12 (bookworm).

Feel free to close the issue.

**Comment by cipherboy** [comment] 2024-07-20 17:36
@in0rdr it might be worthwhile to add this to the known issues section for the time being tbh. Then I'll close it :-) 

But it looks like we don't have an existing known issues space so we'll have to create one first

**Closed** 2024-07-21 18:26 UTC
Labels: bug

**Comment by IohannesArnold** [comment] 2024-07-25 04:17
This is beyond me really but I at least want to thank you for bringing this issue up, which motivated me to learn more about the details of Linux capabilities. :) Not that it helped me understand what was going on. :(

@cipherboy I believe the reason for the indirect reference to mlock in the main project is because the main project depends on the sdk, and I left the mlock code untouched in the sdk because I didn't feel there was a consensus on whether or not plugins built against the Openbao sdk should work with Hashi Vault. If that question is settled in the negative, then we can stub out the mlock code in the sdk, which should remove the mlock dependency totally.
