### ISSUE TITLE
Page not found for pre-compiled binaries

### ISSUE THREAD

**Issue by Th3Tul1p3** [openbao/openbao#326] opened 2024-05-06 13:53 UTC
**Describe the bug**
When we want to download Openbao as precompiled binary, the download link on [page](https://openbao.org/docs/install/#precompiled-binaries) is sending a Page not Found.

**To Reproduce**
1. go on https://openbao.org/
2. [Try it out](https://openbao.org/docs/install/)
3. [precompiled binary](https://openbao.org/docs/install/#precompiled-binaries).
4. and then first lign of first paragraph [download](https://openbao.org/downloads/)

**Expected behavior**
Permit user to download pre-compiled binaries.

**Environment:**
* Brave Browser

**Comment by maulinglawns** [comment] 2024-05-07 05:19
That is due to the cause that there _are_ no official releases yet.
If you want to download a pre-compiled binary *now*, head to:
https://github.com/openbao/openbao/releases
Click **Assets**
Under **Assets** you can download a pre-release. For instance:
`openbao_2.0.0-alpha20240329_linux_amd64.zip`

**Comment by JanMa** [comment] 2024-05-07 20:35
Once #302 is merged those links will work :-)

**Closed** 2024-05-24 21:16 UTC
Labels: bug
